export const sets = [
  { name: 'Detective Pikachu', id: 'det1' },
  { name: 'Dragons Exalted', id: 'bw6' },
  { name: 'Heart Gold & Soul Silver', id: 'hgss1' },
  { name: 'Dragon Majesty', id: 'sm75' },
  { name: 'Crimson Invasion', id: 'sm4' },
  { name: 'Hidden Fates', id: 'sm115' },
  { name: 'Team Up', id: 'sm9' },
  { name: 'Shiny Vault', id: 'sma' },
  { name: 'Legendary Treasures', id: 'bw11' },
  { name: 'Pop Series 5', id: 'pop5' },
  { name: 'Evolutions', id: 'xy12' },
  { name: 'Boundaries Crossed', id: 'bw7' },
  { name: 'Burning Shadows', id: 'sm3' },
  { name: 'Team Rocket Returns', id: 'ex7' },
  { name: 'Rebel Clash', id: 'swsh2' },
  { name: 'Vivid Voltage', id: 'swsh4' },
  { name: 'Base', id: 'base1' },
  { name: 'Crystal Guardians', id: 'ex14' },
  { name: 'Holon Phantoms', id: 'ex13' },
  { name: 'Team Rocket', id: 'base5' },
  { name: 'Power Keepers', id: 'ex16' },
  { name: 'Arceus', id: 'pl4' },
  { name: 'Gym Challenge', id: 'gym2' },
  { name: 'Gym Heroes', id: 'gym1' },
  { name: 'Firered & Leafgreen', id: 'ex6' },
  { name: 'Expedition Base Set', id: 'ecard1' },
  { name: 'Base Set 2', id: 'base4' },
  { name: 'Legendary Collection', id: 'base6' },
  { name: 'Secret Wonders', id: 'dp3' },
  { name: 'XY Black Star Promos', id: 'xyp' },
  { name: 'Mysterious Treasures', id: 'dp2' },
  { name: 'Breakpoint', id: 'xy9' },
  { name: 'Generations', id: 'g1' },
  { name: 'Dragon', id: 'ex3' },
  { name: 'Stormfront', id: 'dp7' },
  { name: 'SWSH Black Star Promos', id: 'swshp' },
  { name: 'Evolving Skies', id: 'swsh7' },
  { name: 'Call Of Legends', id: 'col1' },
  { name: 'Deoxys', id: 'ex8' },
  { name: 'Skyridge', id: 'ecard3' },
  { name: 'Ancient Origins', id: 'xy7' },
];
